application: eastwind-app
version: pi3
runtime: python
api_version: 1

handlers:
- url: /
  script: index.py

- url: /download
  script: index.py

- url: /upload
  script: index.py

- url: /stylesheets
  static_dir: stylesheets

